language: minimal

before_install:
- apt-get -y --force-yes install --no-install-recommends texlive texlive-latex-recommended texlive-latex-extra texlive-xetex texlive-luatex texlive-lang-european texlive-lang-french texlive-humanities texlive-extra-utils texlive-fonts-extra fonts-linuxlibertine lmodern texlive-metapost texlive-music latexmk lilypond pandoc lua

script:
- make manual