dist: xenial

language: minimal

before_install:
- echo deb http://fr.archive.ubuntu.com/ubuntu/ devel main restricted universe multiverse | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get -y --force-yes install --no-install-recommends texlive texlive-latex-recommended texlive-latex-extra texlive-xetex texlive-luatex texlive-lang-european texlive-lang-french texlive-humanities texlive-extra-utils texlive-fonts-extra fonts-linuxlibertine lmodern texlive-metapost texlive-music latexmk lilypond pandoc lua5.1 python-pip
- sudo pip install pygments

script:
- make manual